### ISSUE TITLE
[Bug]: The miactl seems not to work if executed from a container

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/miactl#179]
### What version or versions you have tested?

0.12.2

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [X] Linux

### What did you expect to happen?

I expect to be able to execute the `miactl` from a container, but the cli is stuck.

### What happened instead?

The `miactl` doesn't work from a container.
I tried to add this pipeline step in a build pipeline on the Mia-Platform Demo Console:
```
delivery:
  stage: deploy
  image: ghcr.io/mia-platform/miactl:v0.12.2

  script:
    - miactl version
    - miactl context set miademo --endpoint https://demo.console.gcp.mia-platform.eu --company-id b933f1ef-5b8e-4adf-a346-24a3b03d13e8 --project-id 661d2389027d8f3c9dbe3c24
    - miactl context use miademo
    - miactl context auth miademo --client-id {{CLIENT_ID}} --client-secret {{CLIENT_SECRET}}
    - miactl deploy DEV --deploy-type smart_deploy --revision development --no-semver -v 5
```

but the `miactl deploy` command remains stuck without logs.
On my local computer, the same commands work (with my personal user or with the service account too).

I tried adding a ping command (`ping demo.console.gcp.mia-platform.eu`) inside the pipeline and it worked. I also tried a `wget` command and it worked, so it isn't probably a networking problem.

I also tried locally using docker but it doesn't work. I tried these:
- using the `golang` docker image and manually installing the `miactl`, locally or from the pipeline &rarr; same result, command stuck without logs, locally or on the pipeline;

- using the `homebrew` docker image  and manually installing the `miactl`, locally or from the pipeline &rarr; same result, command stuck without logs, locally or on the pipeline;

- using the `miactl` docker image &rarr; same result, command stuck without logs, locally or on the pipeline.

Can be that the `miactl`, during the login process, even if you are using a `service account`, tries the "user" login flow and, when the Identity Provider tries to go back on `localhost:...`, remains stuck?

Let me know please.

### Code of Conduct

- [X] I agree to follow this project’s Code of Conduct
